name: Run Postman Collection

on:
  push:
    branches:
      - main

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Collection
        run: |
          newman run "Booking API Collection.postman_collection.json" \
          -e "Booking Environment.postman_environment.json"
