name: Postman API Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: npm install -g newman

      - run: |
          node -v
          npm -v
          newman -v

      - run: |
          newman run "Booking API Collection.postman_collection.json" \
          -e "Booking API Environment.postman_environment.json"
